### ISSUE TITLE
mediafire.js - user/upgrade_session_token.php error: Unknown or invalid API method

### ISSUE THREAD

**Issue by TiagoPortfolio** [MediaFire/mediafire-javascript-sdk#7]
Hello everyone!

This API call user/upgrade_session_token.php (mediafire.js line 297) is giving error 253 on any api version:
message: "Unknown or invalid API method",
error: 253

And there isn't any documentation about this call...

**Comment by Daviejoe100** [comment]
[MediaFire+-+Getting+Started.pdf](https://github.com/MediaFire/mediafire-javascript-sdk/files/1521730/MediaFire.-.Getting.Started.pdf)
